### ISSUE TITLE
Shade with holes cannot be translated to OSM

### ISSUE THREAD

**Issue by MingboPeng** [ladybug-tools/honeybee-energy#238] opened 2020-06-24 02:14 UTC
![image](https://user-images.githubusercontent.com/9031066/85489992-ecc4c480-b59e-11ea-9bf6-a4589ff80f72.png)

**Comment by chriswmackey** [comment] 2020-06-29 17:17
We already established that this is not a bug in honeybee-energy.  The exported OSM and IDF are all correct and include the holes.  It's a bug in the Openstudio viewer, which is based on @theo-armour 's viewer.

So I am closing this issue.

**Closed by chriswmackey** 2020-06-29 17:17 UTC
Labels: bug
