### ISSUE TITLE
“Failed to write in IDF to file” while runnning EnergyPlus

### ISSUE THREAD

**Issue by Clukay416** [ladybug-tools/honeybee-energy#1004] opened 2024-04-06 17:08 UTC
Modeling Platform: Rhino 7.36
LBT Version:1.4.0

I am running a sumulation for a mid-rise apartment. When running the energy plus simulation I encountered the following error: **Failed to write in.idf to file:**
I would appreciate any sort of suggestion/help that you can give me.

![01](https://github.com/ladybug-tools/honeybee-energy/assets/135420277/13149e84-433f-4756-9635-f6d083ec4a74)
![01](https://github.com/ladybug-tools/honeybee-energy/assets/135420277/0518fa10-3dc3-4316-80bb-7f80eb6a00bd)
![02](https://github.com/ladybug-tools/honeybee-energy/assets/135420277/c0a51643-e6e1-4251-9252-5b561dd07ea9)

**Comment by JunfXiao** [comment] 2024-04-09 14:18
This is mainly caused by non-ascii characters, like characters in Chinese or "ä", "ö" etc. The related code is under repository [ladybug-tools/ladybug](https://github.com/ladybug-tools/ladybug/tree/c47ab17495dbe72a0c07e6839c654f17b02013c6/ladybug):

https://github.com/ladybug-tools/ladybug/blob/c47ab17495dbe72a0c07e6839c654f17b02013c6/ladybug/futil.py#L111-L116

A temporary solution for you is to check and rename all encountered non-ascii characters, and make sure everything is english letters, numbers or symbols. 

The permanent solution is to specify `encoding='UTF-8'`  when opening the file. To suggest that, you can raise an issue in [this repo](https://github.com/ladybug-tools/ladybug/).

**Comment by chriswmackey** [comment] 2024-04-17 22:28
Sorry for the late response but you are using a version of the software that is almost 3 years old and I am fairly certain that this is already fixed. I can't recreate it either by putting non-ASCII characters into the honeybee model. Nor can I recreate it by putting them into the EPW path:

![image](https://github.com/ladybug-tools/honeybee-energy/assets/5567574/e25338f8-540f-447e-8938-5dd65e074f5f)

So I am going to close this issue. If I'm wrong and you are able to recreate the error in the latest version of the plugin (LBT 1.8), then I recommend posting to the forum with a sample Grasshopper file that recreates the issue:

https://discourse.ladybug.tools/

There, we can see if there is actually a bug and, if so, we can open an issue on GitHub.

**Closed by chriswmackey** 2024-04-17 22:28 UTC
